version: '2'
services:
    expocr-app:
        image: expocr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://expocr-mysql:3306/expocr?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    expocr-mysql:
        extends:
            file: mysql.yml
            service: expocr-mysql
